### ISSUE TITLE
can't resize window

### ISSUE THREAD

**Issue by JerryGoyal** [iconify/iconify-figma#12]
I am not able to resize the window to smaller height, right now window is too big and the import button is overflown/hidden on my laptop. screenshot attached:

notice the blue button on the lower right corner.
![image](https://user-images.githubusercontent.com/7106086/71554317-a2291c00-2a43-11ea-9c96-9835598ff1b8.png)

**Comment by cyberalien** [comment]
That's limitation of Figma plug-ins. Plugin window is not resizable. But there are several workarounds:

1. In menu select options (click button in top left corner), then enable compact layout.

2. Instead of clicking Import button you can drag icon from plug-in to Figma. You can drag icons from icons list and from selected icon sample.

**Comment by cyberalien** [comment]
I've just published new version. It will automatically enable compact layout if it detects that Figma window isn't big enough to fit full UI.

**Comment by cyberalien** [comment]
Another update that changes this behaviour.

In today's update:
* Compact layout option has been replaced by compact width option. It affects only UI width.
* UI height is now dynamic. Plug-in detects Figma window height and sets plug-in UI height to match it.

Please check if plug-in works well for you after this update. Another user asked for possibility to use full layout on small laptop window, so I'm trying to find solution that will work for everyone.

**Comment by JerryGoyal** [comment]
yes, it works now. your plugin height fits the screen now.
