### ISSUE TITLE
Since 2 days I am not seeing the option to scale the iconify window in the options. This is creating major issues

### ISSUE THREAD

**Issue by mukul23** [iconify/iconify-figma#13]
Hey @cyberalien I appreciate the new updates that you bring and this is my most used Figma plugin. However since few days the Iconify window after opening becomes unusably small and previously I could fix it by changing the layout options however there is no such option when I am checking now? Please help and bring it back. My laptop is 14 inch (1280 * 720)

**Comment by cyberalien** [comment]
This was a recent change to fix this issue: https://github.com/iconify/iconify-figma/issues/12

Plugin in full mode has window height of 800, but Figma doesn't scroll window, so in full mode at your resolution you won't see buttons in footer. To fix that, in last update I've added function to detect Figma window size and force compact mode if window is too small to show full mode. Because compact mode is forced, option no longer works, so plug-in no longer shows that option.

I'll find a solution that will make it possible to use full mode on small resolution.

**Comment by cyberalien** [comment]
I've just published update that should solve this issue.

In this update:
* Compact layout option has been replaced by compact width option. It affects only UI width.
* UI height is now dynamic. Plug-in detects Figma window height and sets plug-in UI height to match it.

**Comment by mukul23** [comment]
Hey @cyberalien the issue is now fixed. Thanks a lot for your hard work and quick response :)
