### ISSUE TITLE
enable Swifticons

### ISSUE THREAD

**Issue by sarahfinucane** [iconify/iconify-figma#14]
https://www.swifticons.com/

**Comment by cyberalien** [comment]
Its a premium set, so it is not possible. Iconify is an open source project and adds only icons that are available with open source licenses.

Also each icon set is automatically updated every day from their sources. That means icon set must be available on some kind of version control system, such as Git or NPM. Icon sets that are not available on GitHub (or similar platforms) or NPM (or similar package managers) cannot be added because it will be impossible to automate maintenance.
