### ISSUE TITLE
Option to minimize plugin window

### ISSUE THREAD

**Issue by MenaiAla** [iconify/iconify-figma#27]
It would be better if you add a minimize button that let us hide the window without closing it.

**Comment by cyberalien** [comment]
I don't think that's possible with Figma plug-ins.

If you know any plugin that does it, please let me know and I'll check how it works.

**Comment by cyberalien** [comment]
Added option in new version of plugin. It has small button in top right corner of navigation, clicking it will change window size to smallest possible.

![plugin-minimize](https://user-images.githubusercontent.com/822287/127765781-22ef9198-2bd1-4bfe-9d13-4dac1efb1b3e.png)

![plugin-minimized](https://user-images.githubusercontent.com/822287/127765807-a434fd24-bba0-4b4f-9b8b-6b15244aeff2.png)

Unfortunately plugin window cannot be made smaller than that.

I will also add option to automatically minimise window after importing icon (Import + Minimize). Just need to figure out how to make it usable because there are already too many buttons: Import, Import + Close and I want to add more (Import as Component, Import as Component + Close, etc...), there there will be button to replace existing icon if user has selected previously imported icon, so there are various combinations of import options and plugin window options.
