### ISSUE TITLE
Replace icon in a component instance

### ISSUE THREAD

**Issue by olivier-fm** [iconify/iconify-figma#31]
When used into a component, the feature for replacing the icon on any instances of this component is throwing an error 
"Error importing [icon name]". The icon is yet imported but not in replacement of the previous icon of the component instance

<img width="1433" alt="Capture d’écran 2022-01-08 à 10 08 05" src="https://user-images.githubusercontent.com/66631769/148736412-b3e45503-1df5-4f1a-ad20-282c438ecc7c.png">
<img width="746" alt="Capture d’écran 2022-01-08 à 10 08 24" src="https://user-images.githubusercontent.com/66631769/148736417-a98f9023-6696-4e6a-acbb-aff49c4cf500.png">
<img width="576" alt="Capture d’écran 2022-01-08 à 10 08 29" src="https://user-images.githubusercontent.com/66631769/148736419-e6377385-1197-44ed-ba83-200727d7bd49.png">

I tried to import icon as a component, same issue.
It's working when i try to replace the icon on the master component but not on an instance of it.

**Comment by cyberalien** [comment]
Thanks for reporting!

I've tested it, Figma prevents plugins from removing layers in component instances, so replacing icon in instance is currently not possible.

I'll try to think of a workaround.

**Comment by cyberalien** [comment]
The only workaround for issue I found is to find original component, add icon to it, then hide it, then in component instance hide old icon and unhide new icon. However, it is very tricky to do in plugin and in some cases (if component is from another file, such as organisation level libraries) even impossible.

It will take a while to fix. Until then, if you need to replace icon in component instance, you have to follow steps above to do it manually.

**Comment by olivier-fm** [comment]
Hi, thanks for this workaround. Unfortunately it's not working fine with auto-layout. When the icon is hidden, the layout is broken.. I will wait for a fix then, thanks again for your help and this plugin ;)

**Comment by cyberalien** [comment]
After more testing, steps above are the only possible solution that can be done with plugin. Plugins can do only the same stuff you can do manually, actually even less because some things like converting to component are not easy to implement, so if solution doesn't work when trying it manually, plugin cannot solve that.

One more possible solution, but it cannot be done via plugin because it requires component to be designed differently: instead of replacing icon, create a new component that contains all possible icons, import all icons to it with same width/height, aligned on top of each other, then show/hide icons in each instance.

**Comment by cyberalien** [comment]
Closing as complete.

Figma still does not allow to import icons to component instance, so workaround above is the only solution.

However, new version of plugin (currently available in this repository, not published in Figma yet) handles layers better, it can detect when layer is not a valid target, so no more error messages. I guess that counts as completion of issue.
