### ISSUE TITLE
Support for custom Iconify API in Figma plugin

### ISSUE THREAD

**Issue by himankpathak** [iconify/iconify-figma#33]
Is there a way to connect custom Iconify API to view icons in Figma?
Possibly upload icons to the custom API as well.

**Comment by cyberalien** [comment]
Not yet. It is planned though.

My first attempt at doing it was a failure, but currently I am working on new API and new Icon Finder (code Figma plugin is based on), which I think will take couple of months to do.

**Comment by fengchuanBIG** [comment]
这个计划有继续吗？非常期待

**Comment by cyberalien** [comment]
> 这个计划有继续吗？非常期待

Not anymore.

Due to massive amount of work, Figma plugin rewrite is currently nowhere near top priority. Current version works very well. Changing it would require way too much time, which I don't have.

Plugin will be rewritten only if Figma changes something in plugin API that would break current version.

Sorry, closing this issue as not planned.
