### ISSUE TITLE
Iconify not working

### ISSUE THREAD

**Issue by nglbrrts** [iconify/iconify-figma#6]
the Iconify plugin does not load properly, I tried re-installing the plugin and the figma app and the problem persist
![Captura de Pantalla 2019-09-10 a la(s) 13 02 24](https://user-images.githubusercontent.com/26555015/64630341-4ae73900-d3cb-11e9-855a-0ec4385bbea3.png)

**Comment by cyberalien** [comment]
This is very strange. Are you behind some kind of firewall that might be blocking some URLs?

**Comment by nglbrrts** [comment]
Not really, that was the last thing I checked, it's all running as usual

**Comment by cyberalien** [comment]
Try this: 

1. Open Figma
2. In menu select Plug-ins -> Development -> Open Console. That should show you console
3. Open Iconify plug-in.

Console should show something like this:
```
Iconify: loading stylesheet: https://fonts.googleapis.com/css?family=PT+Sans
Iconify: loading stylesheet: https://code.iconify.design/search/1/1.0.3/style.css
Iconify: loading script: https://code.iconify.design/1/1.0.2/iconify.min.js
Iconify: loading script: https://code.iconify.design/samples.js
Iconify: loading script: https://code.iconify.design/search/1/1.0.3/search.min.js
Iconify debug: loaded all scripts, testing all dependencies...
Iconify debug: tested all dependencies, calling done()
```
Do you get same full log or does it stop at some point? Also can you try opening https://code.iconify.design/search/1/1.0.3/style.css in browser to see if URL is working for you?

**Comment by nglbrrts** [comment]
Ok, so the console shows this
![Captura de Pantalla 2019-09-10 a la(s) 13 23 36](https://user-images.githubusercontent.com/26555015/64631798-38baca00-d3ce-11e9-8676-df441f07d789.png)

The style.css in browser works ok

**Comment by cyberalien** [comment]
Can you check that link in Google Chrome browser?

**Comment by cyberalien** [comment]
If that link works fine in Google Chrome browser (other browsers might not throw error), there is some difference between how Figma and real browser open links. Then maybe Figma developers can solve this. Could be some small hard to spot bug somewhere.

Error message is definitely incorrect. Those files are served by CloudFlare, which always compresses files and sends correct headers. Origin servers for code and api (2 links that fail) are different, but both have correct configuration and work correctly. Also other links do work fine, so this is all very very weird.

I suspect it might be something in your internet connection messes with delivered content. Could be some malware that hijacks internet in order to change ads to its own.

If your computer is clean, I have no idea what could it be. Probably best option is to wait, maybe bug will sort out itself.

**Comment by nglbrrts** [comment]
Yeah, the links work fine in chrome and firefox, I'm gonna check my computer for malware,
Thank you for the help!

**Comment by modymok** [comment]
I have the same issue but the console did show any error's 
![image](https://user-images.githubusercontent.com/10100913/64688111-5a7e8480-d494-11e9-8737-320f50c521a8.png)

**Comment by cyberalien** [comment]
Weird. Are you getting exactly the same messed up layout as nglbrrts or something else?

**Comment by nglbrrts** [comment]
I couldn't find any malware, so I tried re-installing again the app, this time using AppCleaner, and it worked

**Comment by vekovacheva** [comment]
Hi, I am using the desktop version of Figma on my Mac and since recently cannot access the plugin anymore. When I go to Plugins > Iconify and click on Iconify nothing happens. There is no loader, no indication of anything, just as I never clicked on it. Is there an issue, or am I doing something wrong? It's weird because before it used to work perfectly fine. Thanks!

**Comment by cyberalien** [comment]
Try reinstalling it or reinstalling Figma. No idea why that would happen, my guess is some cache in browser got messed up.

**Comment by vekovacheva** [comment]
Hi cyberalien, so I did uninstall and reinstall the desktop app as you suggested and the problem is still not solved. The plugin works well in the browser though. 
Regards, Veronika.

**Comment by cyberalien** [comment]
See if Figma reports any error messages. See my post in this thread about 10 posts above that gives instructions on how to open console.

**Comment by cyberalien** [comment]
New completely rewritten version of plugin has been published. Please check if it solves your issues.
